### ISSUE TITLE
eqmac2 loses state on output device MacBook Pro

### ISSUE THREAD

**Issue by jameyers4** [romankisil/eqmac-webpage#1]
Using eqmac2 on my MacBook 2016 w/ touchbar (4 thunderbolt ports).  Sierra 10.12.6.  Works very well except when I restart the OS, my preferred bluetooth audio output device is not preserved, and requires manual intervention to restore audio output.

Please let me know if I can provide further useful information.

**Comment by romankisil** [comment]
Thanks for the report. I will take a look tomorrow

**Comment by jameyers4** [comment]
Sure.  You have no idea how long I've been looking for a tool like this...
Even though I'm currently unemployed, I did contribute what I could.  Thank
you for doing this.

Please lmk if you need more info.

Best,

Jeff

Please excuse brevity and typos, as this was sent from a mobile device.

**Comment by romankisil** [comment]
I've just realised, you submitted this issue on the wrong repo. This should belong on the https://github.com/romankisil/eqMac2 repo, no worries though I will transfer it there. 
Regarding the contribution, I appreciate any help I get (and yours was the biggest since the new release) So THANK YOU!

**Comment by jameyers4** [comment]
Sure.  Sorry about the incorrect repro... It's been that kind of day.

My pleasure - wish circumstances would have allowed a bit more.

Best,

Jeff

Please excuse brevity and typos, as this was sent from a mobile device.
