### ISSUE TITLE
have to select eqMac2 in the sound System Preferences with each boot

### ISSUE THREAD

**Issue by postmarktv** [romankisil/eqmac-webpage#3]
I like this app very much but it seems that with every new boot of the computer I need to go to the Sound preferences panel and select "headphones" (which I use) it then snaps back to eqMac2 and the sound works. This is not required for the Chrome browser but is required for firefox and some other Mac apps.

thanks!

**Comment by romankisil** [comment]
This is not the repo related to the app, closing

**Comment by postmarktv** [comment]
not sure what's meant by this. The problem I'm reporting is related to the app because the app makes my computer silent until I reselect my sound output.

**Comment by craigster1991** [comment]
This is not the repository for the application code. This is the repository for the website.
To report an issue on the application, please raise the issue on this repository: https://github.com/romankisil/eqMac2
